name: Export Pandoc slideshows

on:
  push:
    branches:
      - master

jobs:
  convert-via-pandoc:
    runs-on: ubuntu-latest
    container:

      image: docker://pandoc/core:2.9
      options: --entrypoint=sh

    steps:

    - name: checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: create output directories
      run: mkdir output

    - name: convert md to tex
      run: |
        find ./ -iname '*.md' -type f -exec sh -c 'pandoc -s -N ${0} -t beamer --slide-level 1 -o output/$(basename $0 .md).tex' {} \;

    - name: LaTeX
      uses: xu-cheng/latex-action@v2
      with:
        working_directory: output
        root_file: "*.tex"
        glob_root_file: true

    - name: Install rsync
      run: |
        apt-get update && apt-get install -y rsync

    - name: Deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: output
        target_folder: slideshow

